name: Testovi

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout koda
      - name: Provera koda
        uses: actions/checkout@v4

      # 2. PHP setup
      - name: Podesavanje PHP-a
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'
          extensions: mbstring, pdo, sqlite
          coverage: none

      # 3. Cache composer paketa
      - name: Kes composer zavisnosti
        uses: actions/cache@v4
        with: 
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 4. Instalacija dependencija
      - name: Instalacija composer paketa
        run: composer install --prefer-dist --no-progress --no-interaction

      # 5. Build Assets
      - name: Build Assets
        run: npm run build

      # 6. Env fajl
      - name: Kopiranje .env.example u .env fajl
        run: cp .env.example .env

      # 7. App key
      - name: Generisanje aplikacijskog kljuca
        run: php artisan key:generate

      # 8. Laravel Pint
      - name: Provera stila koda (Pint)
        run: ./vendor/bin/pint

      # 9. Testovi
      - name: Pokretanje testova
        run: php artisan test
